storage:
  # Available: sqlite, mysql
  type: 'sqlite'

  sqlite:
    database: 'data.db'

  mysql:
    host: 'localhost'
    port: 3306
    user: 'root'
    password: 'password'
    database: 'skillcard'